// Mocks generated by Mockito 5.4.6 from annotations
// in Trivvy/test/testFeatures/Discovery/TestDiscovery.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:Trivvy/features/discovery/application/dto/KahootSearchresponseDto.dart'
    as _i3;
import 'package:Trivvy/features/discovery/application/model/kahoot_Model.dart'
    as _i7;
import 'package:Trivvy/features/discovery/infraestructure/dataSource/kahootRemoteDataSource.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeKahootSearchResponseDto_1 extends _i1.SmartFake
    implements _i3.KahootSearchResponseDto {
  _FakeKahootSearchResponseDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KahootRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockKahootRemoteDataSource extends _i1.Mock
    implements _i4.KahootRemoteDataSource {
  MockKahootRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  _i2.Client get cliente =>
      (super.noSuchMethod(
            Invocation.getter(#cliente),
            returnValue: _FakeClient_0(this, Invocation.getter(#cliente)),
          )
          as _i2.Client);

  @override
  _i6.Future<_i3.KahootSearchResponseDto> fetchKahoots({
    String? query,
    List<String>? themes = const [],
    String? orderBy = 'createdAt',
    String? order = 'desc',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchKahoots, [], {
              #query: query,
              #themes: themes,
              #orderBy: orderBy,
              #order: order,
            }),
            returnValue: _i6.Future<_i3.KahootSearchResponseDto>.value(
              _FakeKahootSearchResponseDto_1(
                this,
                Invocation.method(#fetchKahoots, [], {
                  #query: query,
                  #themes: themes,
                  #orderBy: orderBy,
                  #order: order,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.KahootSearchResponseDto>);

  @override
  _i6.Future<List<_i7.KahootModel>> fetchFeaturedKahoots({int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#fetchFeaturedKahoots, [], {#limit: limit}),
            returnValue: _i6.Future<List<_i7.KahootModel>>.value(
              <_i7.KahootModel>[],
            ),
          )
          as _i6.Future<List<_i7.KahootModel>>);
}
